apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 3
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 3
            httpGet:
              path: /healthz
              port: http
          env:
            - name: DB_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: DB_PROTOCOL
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: DB_USER
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: DB_PWD
            - name: DB_TLS
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: DB_TLS
            - name: DB_STATS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: DB_STATS_API_KEY
            - name: SERVER_PORT
              value: {{ .Values.containerPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "helm.fullname" . }}-configmap
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
